# QUESTION 2

In [55]:
#import necessary libraries
import numpy as np
import scipy as sc

In [56]:
#define coefficient of matrix A
A = np.array([[2,4,6],[5,3,2],[7,8,9]])


In [57]:
print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [58]:
#define coefficient of matrix B
B= np.array ([[18],[13],[30]])

In [59]:
print(B)

[[18]
 [13]
 [30]]


In [72]:
# Use solve function to find solution vector of matrix directly
C= np.linalg.solve(A,B)

In [73]:
print(C)

[[ 4.5]
 [-7.5]
 [ 6.5]]


In [74]:
#ALternatively calculate inv A and multiply with B to find solution vector of the matrix
C= np.linalg.inv(A).dot(B)

In [75]:
print(C)

[[ 4.5]
 [-7.5]
 [ 6.5]]
